# Generated by Django 4.1.7 on 2023-02-22 09:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0003_alter_question_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.AlterUniqueTogether(
            name='quiz_allocation',
            unique_together={('user', 'quiz', 'diff_level')},
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ManyToManyField(to='quiz.quiz'),
        ),
    ]
